In [1]:
import csv
import numpy as np

In [2]:
csv_file = 'C:/Users/Taboada.r248/Documents/LabVIEW Projects/LabVIEW-2024-and-Python/csv_data/low-3.csv'
# csv_file = 'D:/LabVIEW/LabVIEW-2024-and-Python/csv_data/low-3.csv'

In [3]:
data = []
with open(csv_file, newline='') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        for element in row:
            data.append(float(element))

In [4]:
data = np.asarray(data)

In [5]:
min_threshold = 10
tolerance = 0.01

In [6]:
close_values = []
close_values_start_index = 0
close_values_end_index = 0

In [7]:
current_group = []
current_group_start_index = 0

In [8]:
for i, val in enumerate(data):
    # Si el valor está por debajo del umbral mínimo, lo ignoramos
    if val < min_threshold:
        # Si hay un grupo actual, verificamos si es el más grande hasta ahora
        if current_group:
            if len(current_group) > len(close_values):
                close_values = current_group
                close_values_start_index = current_group_start_index
                close_values_end_index = i - 1
            current_group = []
        continue

    # Si el grupo actual está vacío o el valor actual es consecutivo al último valor del grupo actual,
    # agregamos el valor al grupo actual
    if not current_group or abs((val - current_group[-1]) / current_group[-1]) <= tolerance:
        current_group.append(val)
        # Si este es el primer valor del grupo, actualizamos el índice de inicio del grupo
        if len(current_group) == 1:
            current_group_start_index = i
    else:
        # Si el valor no es consecutivo, verificamos si el grupo actual es el más grande hasta ahora
        if len(current_group) > len(close_values):
            close_values = current_group
            close_values_start_index = current_group_start_index
            close_values_end_index = i - 1
        # Reiniciamos el grupo actual con el valor actual
        current_group = [val]
        current_group_start_index = i

In [9]:
if len(current_group) > len(close_values):
    close_values = current_group
    close_values_start_index = current_group_start_index
    close_values_end_index = len(data) - 1

In [10]:
close_values_w_zero = np.zeros_like(data)
if close_values:
    for i in range(close_values_start_index, close_values_end_index + 1):
        close_values_w_zero[i] = data[i]

In [11]:
close_values = np.array(close_values)
num_elements_found = close_values.size

In [12]:
if close_values.size > 0:  # Verifica si el ndarray no está vacío
    average = np.mean(close_values)
else:
    average = -1

In [13]:
data, close_values_w_zero, num_elements_found, close_values, average

(array([ 6.503,  6.482,  6.509, 24.033, 41.957, 58.5  , 75.142, 91.807,
        90.699, 89.471, 87.812, 76.483, 65.182, 53.953, 42.611, 37.631,
        41.934, 46.134, 50.45 , 54.778, 54.483, 54.528, 54.678, 54.785,
        54.846, 53.998, 53.135, 52.179, 50.695, 49.189, 48.632, 48.044,
        47.444, 47.344, 47.377, 47.388, 47.439, 47.63 , 47.8  , 47.849,
        48.045, 48.195, 48.08 , 48.221, 48.271, 48.185, 48.255, 48.48 ,
        48.586, 48.726]),
 array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        47.444, 47.344, 47.377, 47.388, 47.439, 47.63 , 47.8  , 47.849,
        48.045, 48.195, 48.08 , 48.221, 48.271, 48.185, 48.255, 48.48 ,
        48.586, 48.726]),
 18,
 array([47.444, 47.344, 47.377, 47.388, 47.439, 47.63 , 47.8  , 47.849,
       