In [120]:
import csv
import numpy as np

In [121]:
csv_file = 'C:/Users/Taboada.r248/Documents/LabVIEW Projects/LabVIEW-2024-and-Python/csv_data/empty.csv'

In [122]:
data = []
with open(csv_file, newline='') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        for element in row:
            data.append(float(element))

In [123]:
data = np.asarray(data)

In [124]:
tolerance = 4
reference = 48

In [125]:
threshold = tolerance * reference / 100

In [126]:
close_data_indices = np.where(np.abs(data - reference) <= threshold)[0]

In [127]:
splits = np.diff(close_data_indices) != 1

In [128]:
groups = np.split(close_data_indices, np.where(splits)[0] + 1)

In [129]:
largest_group_index = max(groups, key=len)

In [130]:
close_values_w_zero = np.zeros_like(data, dtype=float)

In [131]:
close_values_w_zero[largest_group_index] = data[largest_group_index]

In [132]:
close_values = close_values_w_zero[close_values_w_zero != 0]

In [133]:
if close_values.size > 0:  # Verifica si el ndarray no está vacío
    average = np.mean(close_values)
else:
    average = -1

In [134]:
num_elements_found = len(largest_group_index)

In [135]:
data, close_values_w_zero, num_elements_found, close_values, average

(array([ 6.606,  6.606,  6.589,  6.623,  6.597,  6.581,  6.542, 24.697,
        42.944, 59.771, 76.679, 93.739, 92.297, 90.852, 90.746, 83.923,
        76.869, 69.696, 61.389, 52.616, 50.01 , 47.013, 44.417, 42.793,
        41.744, 44.685, 48.094, 51.47 , 54.919, 58.381, 58.325, 58.256,
        58.399, 58.525, 58.66 , 57.545, 56.393, 55.106, 53.011, 51.038,
        50.361, 49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
        49.366, 49.424]),
 array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   , 49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
        49.366, 49.424]),
 9,
 array([49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358, 49.366,
        