In [1]:
import csv
import numpy as np

In [2]:
csv_file = 'C:/Users/Taboada.r248/Documents/LabVIEW Projects/LabVIEW-2024-and-Python/csv_data/low-1.csv'

In [3]:
data = []
with open(csv_file, newline='') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        for element in row:
            data.append(float(element))

In [4]:
data = np.asarray(data)

In [5]:
tolerance = 4

In [6]:
reference = 48

In [7]:
threshold = tolerance * reference / 100

In [8]:
close_data_indices = np.where(np.abs(data - reference) <= threshold)[0]

In [9]:
close_data_indices

array([21, 26, 41, 42, 43, 44, 45, 46, 47, 48, 49], dtype=int32)

In [10]:
splits = np.diff(close_data_indices) != 1

In [11]:
splits

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [12]:
groups = np.split(close_data_indices, np.where(splits)[0] + 1)

In [13]:
largest_group_index = max(groups, key=len)

In [14]:
largest_group_index

array([41, 42, 43, 44, 45, 46, 47, 48, 49], dtype=int32)

In [15]:
close_values_w_zero = np.zeros_like(data, dtype=float)

In [16]:
close_values_w_zero[largest_group_index] = data[largest_group_index]

In [17]:
close_values = close_values_w_zero[close_values_w_zero != 0]

In [18]:
average = np.mean(close_values)

In [19]:
num_elements_found = len(largest_group_index)

In [20]:
data

array([ 6.606,  6.606,  6.589,  6.623,  6.597,  6.581,  6.542, 24.697,
       42.944, 59.771, 76.679, 93.739, 92.297, 90.852, 90.746, 83.923,
       76.869, 69.696, 61.389, 52.616, 50.01 , 47.013, 44.417, 42.793,
       41.744, 44.685, 48.094, 51.47 , 54.919, 58.381, 58.325, 58.256,
       58.399, 58.525, 58.66 , 57.545, 56.393, 55.106, 53.011, 51.038,
       50.361, 49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
       49.366, 49.424])

In [21]:
close_values_w_zero

array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   , 49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
       49.366, 49.424])

In [22]:
num_elements_found

9

In [23]:
close_values

array([49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358, 49.366,
       49.424])

In [24]:
average

49.291