In [85]:
import csv
import numpy as np

In [86]:
csv_file = 'C:/Users/Taboada.r248/Documents/LabVIEW Projects/LabVIEW-2024-and-Python/csv_data/low-1.csv'

In [87]:
data = []
with open(csv_file, newline='') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        for element in row:
            data.append(float(element))

In [88]:
data = np.asarray(data)

In [89]:
min_threshold = 10
tolerance = 0.01

In [90]:
close_values = []
close_values_start_index = 0
close_values_end_index = 0

In [91]:
current_group = []
current_group_start_index = 0

In [92]:
for i, val in enumerate(data):
    # Si el valor está por debajo del umbral mínimo, lo ignoramos
    if val < min_threshold:
        # Si hay un grupo actual, verificamos si es el más grande hasta ahora
        if current_group:
            if len(current_group) > len(close_values):
                close_values = current_group
                close_values_start_index = current_group_start_index
                close_values_end_index = i - 1
            current_group = []
        continue

    # Si el grupo actual está vacío o el valor actual es consecutivo al último valor del grupo actual,
    # agregamos el valor al grupo actual
    if not current_group or abs((val - current_group[-1]) / current_group[-1]) <= tolerance:
        current_group.append(val)
        # Si este es el primer valor del grupo, actualizamos el índice de inicio del grupo
        if len(current_group) == 1:
            current_group_start_index = i
    else:
        # Si el valor no es consecutivo, verificamos si el grupo actual es el más grande hasta ahora
        if len(current_group) > len(close_values):
            close_values = current_group
            close_values_start_index = current_group_start_index
            close_values_end_index = i - 1
        # Reiniciamos el grupo actual con el valor actual
        current_group = [val]
        current_group_start_index = i

In [93]:
if len(current_group) > len(close_values):
    close_values = current_group
    close_values_start_index = current_group_start_index
    close_values_end_index = len(data) - 1

In [94]:
close_values_w_zero = np.zeros_like(data)
if close_values:
    for i in range(close_values_start_index, close_values_end_index + 1):
        close_values_w_zero[i] = data[i]

In [95]:
close_values = np.array(close_values)
num_elements_found = close_values.size

In [96]:
if close_values.size > 0:  # Verifica si el ndarray no está vacío
    average = np.mean(close_values)
else:
    average = -1

In [97]:
data, close_values_w_zero, num_elements_found, close_values, average

(array([ 6.606,  6.606,  6.589,  6.623,  6.597,  6.581,  6.542, 24.697,
        42.944, 59.771, 76.679, 93.739, 92.297, 90.852, 90.746, 83.923,
        76.869, 69.696, 61.389, 52.616, 50.01 , 47.013, 44.417, 42.793,
        41.744, 44.685, 48.094, 51.47 , 54.919, 58.381, 58.325, 58.256,
        58.399, 58.525, 58.66 , 57.545, 56.393, 55.106, 53.011, 51.038,
        50.361, 49.681, 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
        49.366, 49.424]),
 array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   , 48.971, 49.107, 49.241, 49.229, 49.242, 49.358,
        49.366, 49.424]),
 8,
 array([48.971, 49.107, 49.241, 49.229, 49.242, 49.358, 49.366, 49.424]),
 49.24