In [200]:
import csv
import numpy as np

In [201]:
csv_file = 'C:/Users/Taboada.r248/Documents/LabVIEW Projects/LabVIEW-2024-and-Python/csv_data/low-3.csv'

In [202]:
data = []
with open(csv_file, newline='') as file:
    csv_reader = csv.reader(file)
    for row in csv_reader:
        for element in row:
            data.append(float(element))

In [203]:
data = np.asarray(data)

In [204]:
tolerance = 4
reference = 48

In [205]:
threshold = tolerance * reference / 100

In [206]:
close_data_indices = np.where(np.abs(data - reference) <= threshold)[0]

In [207]:
splits = np.diff(close_data_indices) != 1

In [208]:
groups = np.split(close_data_indices, np.where(splits)[0] + 1)

In [209]:
largest_group_index = max(groups, key=len)

In [210]:
close_values_w_zero = np.zeros_like(data, dtype=float)

In [211]:
close_values_w_zero[largest_group_index] = data[largest_group_index]

In [212]:
close_values = close_values_w_zero[close_values_w_zero != 0]

In [213]:
if close_values.size > 0:  # Verifica si el ndarray no está vacío
    average = np.mean(close_values)
else:
    average = -1

In [214]:
num_elements_found = len(largest_group_index)

In [215]:
data, close_values_w_zero, num_elements_found, close_values, average

(array([ 6.503,  6.482,  6.509, 24.033, 41.957, 58.5  , 75.142, 91.807,
        90.699, 89.471, 87.812, 76.483, 65.182, 53.953, 42.611, 37.631,
        41.934, 46.134, 50.45 , 54.778, 54.483, 54.528, 54.678, 54.785,
        54.846, 53.998, 53.135, 52.179, 50.695, 49.189, 48.632, 48.044,
        47.444, 47.344, 47.377, 47.388, 47.439, 47.63 , 47.8  , 47.849,
        48.045, 48.195, 48.08 , 48.221, 48.271, 48.185, 48.255, 48.48 ,
        48.586, 48.726]),
 array([ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.   , 49.189, 48.632, 48.044,
        47.444, 47.344, 47.377, 47.388, 47.439, 47.63 , 47.8  , 47.849,
        48.045, 48.195, 48.08 , 48.221, 48.271, 48.185, 48.255, 48.48 ,
        48.586, 48.726]),
 21,
 array([49.189, 48.632, 48.044, 47.444, 47.344, 47.377, 47.388, 47.439,
       